id: AA08A0C48
title: ยง22
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:17:31.275337
  last_modified_at: 2022-03-01 21:17:31.275340
