id: AA08A0C48
title: ยง6
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:17:31.282769
  last_modified_at: 2022-03-01 21:17:31.282772
