id: AA08A0C48
title: ยง11
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:17:31.260503
  last_modified_at: 2022-03-01 21:17:31.260508
